package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * AlbumLiked generated by hbm2java
 */
public class AlbumLiked implements java.io.Serializable {

	private AlbumLikedId id;
	private Album album;
	private User user;

	public AlbumLiked() {
	}

	public AlbumLiked(AlbumLikedId id, Album album) {
		this.id = id;
		this.album = album;
	}

	public AlbumLiked(AlbumLikedId id, Album album, User user) {
		this.id = id;
		this.album = album;
		this.user = user;
	}

	public AlbumLikedId getId() {
		return this.id;
	}

	public void setId(AlbumLikedId id) {
		this.id = id;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
