package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * AlbumIncluded generated by hbm2java
 */
public class AlbumIncluded implements java.io.Serializable {

	private AlbumIncludedId id;
	private Album album;
	private Picture picture;

	public AlbumIncluded() {
	}

	public AlbumIncluded(AlbumIncludedId id, Album album) {
		this.id = id;
		this.album = album;
	}

	public AlbumIncluded(AlbumIncludedId id, Album album, Picture picture) {
		this.id = id;
		this.album = album;
		this.picture = picture;
	}

	public AlbumIncludedId getId() {
		return this.id;
	}

	public void setId(AlbumIncludedId id) {
		this.id = id;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

}
