package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Albums generated by hbm2java
 */
public class Albums implements java.io.Serializable {

	private Integer albumId;
	private Users users;
	private int picNum;
	private Date setDate;
	private String description;
	private String coverPath;
	private String theme;
	private Set albumLikeds = new HashSet(0);
	private Set albumIncludeds = new HashSet(0);

	public Albums() {
	}

	public Albums(Users users, int picNum, Date setDate, String theme) {
		this.users = users;
		this.picNum = picNum;
		this.setDate = setDate;
		this.theme = theme;
	}

	public Albums(Users users, int picNum, Date setDate, String description,
			String coverPath, String theme, Set albumLikeds, Set albumIncludeds) {
		this.users = users;
		this.picNum = picNum;
		this.setDate = setDate;
		this.description = description;
		this.coverPath = coverPath;
		this.theme = theme;
		this.albumLikeds = albumLikeds;
		this.albumIncludeds = albumIncludeds;
	}

	public Albums(Users users2, Date setDate2, String theme2,
			String description2) {
		// TODO Auto-generated constructor stub
		this.users = users2;
		this.setDate = setDate2;
		this.theme = theme2;
		this.description = description2;
	}

	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getPicNum() {
		return this.picNum;
	}

	public void setPicNum(int picNum) {
		this.picNum = picNum;
	}

	public Date getSetDate() {
		return this.setDate;
	}

	public void setSetDate(Date setDate) {
		this.setDate = setDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCoverPath() {
		return this.coverPath;
	}

	public void setCoverPath(String coverPath) {
		this.coverPath = coverPath;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public Set getAlbumLikeds() {
		return this.albumLikeds;
	}

	public void setAlbumLikeds(Set albumLikeds) {
		this.albumLikeds = albumLikeds;
	}

	public Set getAlbumIncludeds() {
		return this.albumIncludeds;
	}

	public void setAlbumIncludeds(Set albumIncludeds) {
		this.albumIncludeds = albumIncludeds;
	}

}
