package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

/**
 * AlbumLiked generated by hbm2java
 */
public class AlbumLiked implements java.io.Serializable {

	private AlbumLikedId id;
	private Albums albums;
	private Users users;

	public AlbumLiked() {
	}

	public AlbumLiked(AlbumLikedId id, Albums albums) {
		this.id = id;
		this.albums = albums;
	}

	public AlbumLiked(AlbumLikedId id, Albums albums, Users users) {
		this.id = id;
		this.albums = albums;
		this.users = users;
	}

	public AlbumLikedId getId() {
		return this.id;
	}

	public void setId(AlbumLikedId id) {
		this.id = id;
	}

	public Albums getAlbums() {
		return this.albums;
	}

	public void setAlbums(Albums albums) {
		this.albums = albums;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
