package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * AlbumIncludedId generated by hbm2java
 */
public class AlbumIncludedId implements java.io.Serializable {

	private int albumId;
	private Integer pictureId;

	public AlbumIncludedId() {
	}

	public AlbumIncludedId(int albumId) {
		this.albumId = albumId;
	}

	public AlbumIncludedId(int albumId, Integer pictureId) {
		this.albumId = albumId;
		this.pictureId = pictureId;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumIncludedId))
			return false;
		AlbumIncludedId castOther = (AlbumIncludedId) other;

		return (this.getAlbumId() == castOther.getAlbumId())
				&& ((this.getPictureId() == castOther.getPictureId()) || (this
						.getPictureId() != null
						&& castOther.getPictureId() != null && this
						.getPictureId().equals(castOther.getPictureId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAlbumId();
		result = 37 * result
				+ (getPictureId() == null ? 0 : this.getPictureId().hashCode());
		return result;
	}

}
