package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

/**
 * FriendsId generated by hbm2java
 */
public class FriendsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int myId;
	private Integer friendId;

	public FriendsId() {
	}

	public FriendsId(int myId) {
		this.myId = myId;
	}

	public FriendsId(int myId, Integer friendId) {
		this.myId = myId;
		this.friendId = friendId;
	}

	public int getMyId() {
		return this.myId;
	}

	public void setMyId(int myId) {
		this.myId = myId;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FriendsId))
			return false;
		FriendsId castOther = (FriendsId) other;

		return (this.getMyId() == castOther.getMyId())
				&& ((this.getFriendId() == castOther.getFriendId()) || (this
						.getFriendId() != null
						&& castOther.getFriendId() != null && this
						.getFriendId().equals(castOther.getFriendId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMyId();
		result = 37 * result
				+ (getFriendId() == null ? 0 : this.getFriendId().hashCode());
		return result;
	}

}
