package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * FriendId generated by hbm2java
 */
public class FriendId implements java.io.Serializable {

	private int myId;
	private Integer friendId;

	public FriendId() {
	}

	public FriendId(int myId) {
		this.myId = myId;
	}

	public FriendId(int myId, Integer friendId) {
		this.myId = myId;
		this.friendId = friendId;
	}

	public int getMyId() {
		return this.myId;
	}

	public void setMyId(int myId) {
		this.myId = myId;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FriendId))
			return false;
		FriendId castOther = (FriendId) other;

		return (this.getMyId() == castOther.getMyId())
				&& ((this.getFriendId() == castOther.getFriendId()) || (this
						.getFriendId() != null
						&& castOther.getFriendId() != null && this
						.getFriendId().equals(castOther.getFriendId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMyId();
		result = 37 * result
				+ (getFriendId() == null ? 0 : this.getFriendId().hashCode());
		return result;
	}

}
