package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * GroupMember generated by hbm2java
 */
public class GroupMember implements java.io.Serializable {

	private GroupMemberId id;
	private Group group;
	private User user;

	public GroupMember() {
	}

	public GroupMember(GroupMemberId id, Group group) {
		this.id = id;
		this.group = group;
	}

	public GroupMember(GroupMemberId id, Group group, User user) {
		this.id = id;
		this.group = group;
		this.user = user;
	}

	public GroupMemberId getId() {
		return this.id;
	}

	public void setId(GroupMemberId id) {
		this.id = id;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
