package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer groupId;
	private User user;
	private String name;
	private Integer memberNum;
	private Date setDate;
	private String theme;
	private Set groupComments = new HashSet(0);
	private Set groupMembers = new HashSet(0);

	public Group() {
	}

	public Group(User user, String name, Date setDate, String theme) {
		this.user = user;
		this.name = name;
		this.setDate = setDate;
		this.theme = theme;
	}

	public Group(User user, String name, Integer memberNum, Date setDate,
			String theme, Set groupComments, Set groupMembers) {
		this.user = user;
		this.name = name;
		this.memberNum = memberNum;
		this.setDate = setDate;
		this.theme = theme;
		this.groupComments = groupComments;
		this.groupMembers = groupMembers;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMemberNum() {
		return this.memberNum;
	}

	public void setMemberNum(Integer memberNum) {
		this.memberNum = memberNum;
	}

	public Date getSetDate() {
		return this.setDate;
	}

	public void setSetDate(Date setDate) {
		this.setDate = setDate;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public Set getGroupComments() {
		return this.groupComments;
	}

	public void setGroupComments(Set groupComments) {
		this.groupComments = groupComments;
	}

	public Set getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set groupMembers) {
		this.groupMembers = groupMembers;
	}

}
