package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

/**
 * GroupMem generated by hbm2java
 */
public class GroupMem implements java.io.Serializable {

	private GroupMemId id;
	private Groups groups;
	private Users users;

	public GroupMem() {
	}

	public GroupMem(GroupMemId id, Groups groups) {
		this.id = id;
		this.groups = groups;
	}

	public GroupMem(GroupMemId id, Groups groups, Users users) {
		this.id = id;
		this.groups = groups;
		this.users = users;
	}

	public GroupMemId getId() {
		return this.id;
	}

	public void setId(GroupMemId id) {
		this.id = id;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
