package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * GroupMemberId generated by hbm2java
 */
public class GroupMemberId implements java.io.Serializable {

	private int groupId;
	private Integer userId;

	public GroupMemberId() {
	}

	public GroupMemberId(int groupId) {
		this.groupId = groupId;
	}

	public GroupMemberId(int groupId, Integer userId) {
		this.groupId = groupId;
		this.userId = userId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupMemberId))
			return false;
		GroupMemberId castOther = (GroupMemberId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
