package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * GroupComment generated by hbm2java
 */
public class GroupComment implements java.io.Serializable {

	private Integer commentId;
	private Groups groups;
	private Users users;
	private Date commentDate;
	private String content;

	public GroupComment() {
	}

	public GroupComment(Groups groups, Users users, Date commentDate,
			String content) {
		this.groups = groups;
		this.users = users;
		this.commentDate = commentDate;
		this.content = content;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
