package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

/**
 * PicLiked generated by hbm2java
 */
public class PicLiked implements java.io.Serializable {

	private PicLikedId id;
	private Pictures pictures;
	private Users users;

	public PicLiked() {
	}

	public PicLiked(PicLikedId id, Pictures pictures) {
		this.id = id;
		this.pictures = pictures;
	}

	public PicLiked(PicLikedId id, Pictures pictures, Users users) {
		this.id = id;
		this.pictures = pictures;
		this.users = users;
	}

	public PicLikedId getId() {
		return this.id;
	}

	public void setId(PicLikedId id) {
		this.id = id;
	}

	public Pictures getPictures() {
		return this.pictures;
	}

	public void setPictures(Pictures pictures) {
		this.pictures = pictures;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
