package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * PictureTagId generated by hbm2java
 */
public class PictureTagId implements java.io.Serializable {

	private String tag;
	private int pictureId;

	public PictureTagId() {
	}

	public PictureTagId(String tag, int pictureId) {
		this.tag = tag;
		this.pictureId = pictureId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public int getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(int pictureId) {
		this.pictureId = pictureId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PictureTagId))
			return false;
		PictureTagId castOther = (PictureTagId) other;

		return ((this.getTag() == castOther.getTag()) || (this.getTag() != null
				&& castOther.getTag() != null && this.getTag().equals(
				castOther.getTag())))
				&& (this.getPictureId() == castOther.getPictureId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		result = 37 * result + this.getPictureId();
		return result;
	}

}
