package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * PictureLiked generated by hbm2java
 */
public class PictureLiked implements java.io.Serializable {

	private PictureLikedId id;
	private Picture picture;
	private User user;

	public PictureLiked() {
	}

	public PictureLiked(PictureLikedId id, Picture picture) {
		this.id = id;
		this.picture = picture;
	}

	public PictureLiked(PictureLikedId id, Picture picture, User user) {
		this.id = id;
		this.picture = picture;
		this.user = user;
	}

	public PictureLikedId getId() {
		return this.id;
	}

	public void setId(PictureLikedId id) {
		this.id = id;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
