package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * PictureLikedId generated by hbm2java
 */
public class PictureLikedId implements java.io.Serializable {

	private int pictureId;
	private Integer userId;

	public PictureLikedId() {
	}

	public PictureLikedId(int pictureId) {
		this.pictureId = pictureId;
	}

	public PictureLikedId(int pictureId, Integer userId) {
		this.pictureId = pictureId;
		this.userId = userId;
	}

	public int getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(int pictureId) {
		this.pictureId = pictureId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PictureLikedId))
			return false;
		PictureLikedId castOther = (PictureLikedId) other;

		return (this.getPictureId() == castOther.getPictureId())
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPictureId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
