package imangine.database.entity;

// Generated 2016-1-14 10:25:48 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pictures generated by hbm2java
 */
public class Pictures implements java.io.Serializable {

	private Integer picId;
	private Users users;
	private String path;
	private Date uploadDate;
	private String title;
	private String description;
	private Set picLikeds = new HashSet(0);
	private Set picComments = new HashSet(0);
	private Set picTags = new HashSet(0);
	private Set albumIncludeds = new HashSet(0);

	public Pictures() {
	}

	public Pictures(String path, Date uploadDate, String title) {
		this.path = path;
		this.uploadDate = uploadDate;
		this.title = title;
	}

	public Pictures(Users users, String path, Date uploadDate, String title,
			String description, Set picLikeds, Set picComments, Set picTags,
			Set albumIncludeds) {
		this.users = users;
		this.path = path;
		this.uploadDate = uploadDate;
		this.title = title;
		this.description = description;
		this.picLikeds = picLikeds;
		this.picComments = picComments;
		this.picTags = picTags;
		this.albumIncludeds = albumIncludeds;
	}

	public Pictures(String path2, Users users2, String title2) {
		// TODO Auto-generated constructor stub
		this.path = path2;
		this.users = users2;
		this.title = title2;
	}

	public Integer getPicId() {
		return this.picId;
	}

	public void setPicId(Integer picId) {
		this.picId = picId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPicLikeds() {
		return this.picLikeds;
	}

	public void setPicLikeds(Set picLikeds) {
		this.picLikeds = picLikeds;
	}

	public Set getPicComments() {
		return this.picComments;
	}

	public void setPicComments(Set picComments) {
		this.picComments = picComments;
	}

	public Set getPicTags() {
		return this.picTags;
	}

	public void setPicTags(Set picTags) {
		this.picTags = picTags;
	}

	public Set getAlbumIncludeds() {
		return this.albumIncludeds;
	}

	public void setAlbumIncludeds(Set albumIncludeds) {
		this.albumIncludeds = albumIncludeds;
	}

}
