package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Picture generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	private Integer pictureId;
	private User user;
	private String path;
	private Date uploadDate;
	private String title;
	private String description;
	private Set pictureComments = new HashSet(0);
	private Set pictureLikeds = new HashSet(0);
	private Set pictureTags = new HashSet(0);
	private Set albumIncludeds = new HashSet(0);

	public Picture() {
	}

	public Picture(String path, Date uploadDate, String title) {
		this.path = path;
		this.uploadDate = uploadDate;
		this.title = title;
	}

	public Picture(User user, String path, Date uploadDate, String title,
			String description, Set pictureComments, Set pictureLikeds,
			Set pictureTags, Set albumIncludeds) {
		this.user = user;
		this.path = path;
		this.uploadDate = uploadDate;
		this.title = title;
		this.description = description;
		this.pictureComments = pictureComments;
		this.pictureLikeds = pictureLikeds;
		this.pictureTags = pictureTags;
		this.albumIncludeds = albumIncludeds;
	}

	public Picture(String path2, User user2, String title2) {
		this.path = path2;
		this.user = user2;
		this.title = title2;
	}

	public Integer getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Integer pictureId) {
		this.pictureId = pictureId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getPictureComments() {
		return this.pictureComments;
	}

	public void setPictureComments(Set pictureComments) {
		this.pictureComments = pictureComments;
	}

	public Set getPictureLikeds() {
		return this.pictureLikeds;
	}

	public void setPictureLikeds(Set pictureLikeds) {
		this.pictureLikeds = pictureLikeds;
	}

	public Set getPictureTags() {
		return this.pictureTags;
	}

	public void setPictureTags(Set pictureTags) {
		this.pictureTags = pictureTags;
	}

	public Set getAlbumIncludeds() {
		return this.albumIncludeds;
	}

	public void setAlbumIncludeds(Set albumIncludeds) {
		this.albumIncludeds = albumIncludeds;
	}

}
