package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

/**
 * PictureTag generated by hbm2java
 */
public class PictureTag implements java.io.Serializable {

	private PictureTagId id;
	private Picture picture;

	public PictureTag() {
	}

	public PictureTag(PictureTagId id, Picture picture) {
		this.id = id;
		this.picture = picture;
	}

	public PictureTagId getId() {
		return this.id;
	}

	public void setId(PictureTagId id) {
		this.id = id;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

}
