package imangine.database.entity;

// Generated 2016-1-14 13:50:25 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * PictureComment generated by hbm2java
 */
public class PictureComment implements java.io.Serializable {

	private Integer commentId;
	private Picture picture;
	private User user;
	private Date commentDate;
	private String content;

	public PictureComment() {
	}

	public PictureComment(Picture picture, User user, Date commentDate,
			String content) {
		this.picture = picture;
		this.user = user;
		this.commentDate = commentDate;
		this.content = content;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
