package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

/**
 * AlbumIncludedId generated by hbm2java
 */
public class AlbumIncludedId implements java.io.Serializable {

	private int albumId;
	private Integer picId;

	public AlbumIncludedId() {
	}

	public AlbumIncludedId(int albumId) {
		this.albumId = albumId;
	}

	public AlbumIncludedId(int albumId, Integer picId) {
		this.albumId = albumId;
		this.picId = picId;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public Integer getPicId() {
		return this.picId;
	}

	public void setPicId(Integer picId) {
		this.picId = picId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumIncludedId))
			return false;
		AlbumIncludedId castOther = (AlbumIncludedId) other;

		return (this.getAlbumId() == castOther.getAlbumId())
				&& ((this.getPicId() == castOther.getPicId()) || (this
						.getPicId() != null && castOther.getPicId() != null && this
						.getPicId().equals(castOther.getPicId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAlbumId();
		result = 37 * result
				+ (getPicId() == null ? 0 : this.getPicId().hashCode());
		return result;
	}

}
