package imangine;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1



/**
 * Albums generated by hbm2java
 */
public class Albums implements java.io.Serializable {

	private Integer albumId;
	private Users users;
	private int picNum;
	private Date setDate;
	private String description;
	private String theme;
	private String coverAdderss;
	private Set albumLikeds = new HashSet(0);
	private Set albumIncludeds = new HashSet(0);

	public Albums() {
	}

	public Albums(Users users, Date setDate, String theme,String description) {
		this.users = users;
		this.setDate = setDate;
		this.theme = theme;
		this.description=description;
	}

	public Albums(Users users, int picNum, Date setDate, String description,
			String theme, Set albumLikeds, Set albumIncludeds) {
		this.users = users;
		this.picNum = picNum;
		this.setDate = setDate;
		this.description = description;
		this.theme = theme;
		this.albumLikeds = albumLikeds;
		this.albumIncludeds = albumIncludeds;
	}

	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getPicNum() {
		return this.picNum;
	}

	public void setPicNum(int picNum) {
		this.picNum = picNum;
	}

	public Date getSetDate() {
		return this.setDate;
	}

	public void setSetDate(Date setDate) {
		this.setDate = setDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public Set getAlbumLikeds() {
		return this.albumLikeds;
	}

	public void setAlbumLikeds(Set albumLikeds) {
		this.albumLikeds = albumLikeds;
	}

	public Set getAlbumIncludeds() {
		return this.albumIncludeds;
	}

	public void setAlbumIncludeds(Set albumIncludeds) {
		this.albumIncludeds = albumIncludeds;
	}

	/**
	 * @return the coverAdderss
	 */
	public String getCoverAdderss() {
		return coverAdderss;
	}

	/**
	 * @param coverAdderss the coverAdderss to set
	 */
	public void setCoverAdderss(String coverAdderss) {
		this.coverAdderss = coverAdderss;
	}

}
