package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

/**
 * AlbumLikedId generated by hbm2java
 */
public class AlbumLikedId implements java.io.Serializable {

	private int albumId;
	private Integer userId;

	public AlbumLikedId() {
	}

	public AlbumLikedId(int albumId) {
		this.albumId = albumId;
	}

	public AlbumLikedId(int albumId, Integer userId) {
		this.albumId = albumId;
		this.userId = userId;
	}

	public int getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(int albumId) {
		this.albumId = albumId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumLikedId))
			return false;
		AlbumLikedId castOther = (AlbumLikedId) other;

		return (this.getAlbumId() == castOther.getAlbumId())
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAlbumId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
