package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

/**
 * Friends generated by hbm2java
 */
public class Friends implements java.io.Serializable {

	private FriendsId id;
	private Users usersByFriendId;
	private Users usersByMyId;

	public Friends() {
	}

	public Friends(FriendsId id, Users usersByMyId) {
		this.id = id;
		this.usersByMyId = usersByMyId;
	}

	public Friends(FriendsId id, Users usersByFriendId, Users usersByMyId) {
		this.id = id;
		this.usersByFriendId = usersByFriendId;
		this.usersByMyId = usersByMyId;
	}

	public FriendsId getId() {
		return this.id;
	}

	public void setId(FriendsId id) {
		this.id = id;
	}

	public Users getUsersByFriendId() {
		return this.usersByFriendId;
	}

	public void setUsersByFriendId(Users usersByFriendId) {
		this.usersByFriendId = usersByFriendId;
	}

	public Users getUsersByMyId() {
		return this.usersByMyId;
	}

	public void setUsersByMyId(Users usersByMyId) {
		this.usersByMyId = usersByMyId;
	}

}
