package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	private Integer groupId;
	private Users users;
	private String name;
	private Integer membership;
	private Date setDate;
	private String theme;
	private Set groupComments = new HashSet(0);
	private Set groupMems = new HashSet(0);

	public Groups() {
	}

	public Groups(Users users, String name, Date setDate, String theme) {
		this.users = users;
		this.name = name;
		this.setDate = setDate;
		this.theme = theme;
	}

	public Groups(Users users, String name, Integer membership, Date setDate,
			String theme, Set groupComments, Set groupMems) {
		this.users = users;
		this.name = name;
		this.membership = membership;
		this.setDate = setDate;
		this.theme = theme;
		this.groupComments = groupComments;
		this.groupMems = groupMems;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMembership() {
		return this.membership;
	}

	public void setMembership(Integer membership) {
		this.membership = membership;
	}

	public Date getSetDate() {
		return this.setDate;
	}

	public void setSetDate(Date setDate) {
		this.setDate = setDate;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public Set getGroupComments() {
		return this.groupComments;
	}

	public void setGroupComments(Set groupComments) {
		this.groupComments = groupComments;
	}

	public Set getGroupMems() {
		return this.groupMems;
	}

	public void setGroupMems(Set groupMems) {
		this.groupMems = groupMems;
	}

}
