package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

/**
 * PicLikedId generated by hbm2java
 */
public class PicLikedId implements java.io.Serializable {

	private int picId;
	private Integer userId;

	public PicLikedId() {
	}

	public PicLikedId(int picId) {
		this.picId = picId;
	}

	public PicLikedId(int picId, Integer userId) {
		this.picId = picId;
		this.userId = userId;
	}

	public int getPicId() {
		return this.picId;
	}

	public void setPicId(int picId) {
		this.picId = picId;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PicLikedId))
			return false;
		PicLikedId castOther = (PicLikedId) other;

		return (this.getPicId() == castOther.getPicId())
				&& ((this.getUserId() == castOther.getUserId()) ||
						(this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPicId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
