package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

/**
 * PicTagId generated by hbm2java
 */
public class PicTagId implements java.io.Serializable {

	private String tag;
	private int picId;

	public PicTagId() {
	}

	public PicTagId(String tag, int picId) {
		this.tag = tag;
		this.picId = picId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public int getPicId() {
		return this.picId;
	}

	public void setPicId(int picId) {
		this.picId = picId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PicTagId))
			return false;
		PicTagId castOther = (PicTagId) other;

		return ((this.getTag() == castOther.getTag()) || (this.getTag() != null
				&& castOther.getTag() != null && this.getTag().equals(
				castOther.getTag())))
				&& (this.getPicId() == castOther.getPicId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		result = 37 * result + this.getPicId();
		return result;
	}

}
