package imangine;

// Generated 2015-6-2 19:52:21 by Hibernate Tools 4.3.1

/**
 * PicTag generated by hbm2java
 */
public class PicTag implements java.io.Serializable {

	private PicTagId id;
	private Pictures pictures;

	public PicTag() {
	}

	public PicTag(PicTagId id, Pictures pictures) {
		this.id = id;
		this.pictures = pictures;
	}

	public PicTagId getId() {
		return this.id;
	}

	public void setId(PicTagId id) {
		this.id = id;
	}

	public Pictures getPictures() {
		return this.pictures;
	}

	public void setPictures(Pictures pictures) {
		this.pictures = pictures;
	}

}
